Feature/sw-1762-syncing-suspended-status-from-synergy
SynergyWholesale/WHMCS-Hosting-Module pull request #4
Opened 2021-01-29 01:35 UTC by LlamaLLamaGoose

2021-01-29 02:01 UTC, Sn0wCrack requested changes
Have one change I'd like you to make.

But can you also update the changelogs? New version will be 1.6.4

Thanks 😄

2021-01-29 02:01 UTC, Sn0wCrack commented on modules/servers/synergywholesale_hosting/synergywholesale_hosting.php
> +            'domainstatus' => $hostingStatus[$apiResult->status] ? $hostingStatus[$apiResult->status] : $params['status'],
```suggestion
            'domainstatus' => isset($hostingStatus[$apiResult->status]) ? $hostingStatus[$apiResult->status] : $params['status'],
```

2021-01-29 02:43 UTC, LlamaLLamaGoose commented
I've updated the changelog :)

2021-01-29 03:08 UTC, Sn0wCrack approved these changes

2021-03-10 05:38 UTC, Luke-McMahon commented
Sorry mate, would you be able to resolve the conflicts that are currently present?
We'll also have to increment the module version again in the changelogs (sorry) -- version will be 1.6.7

2021-03-16 02:08 UTC, Luke-McMahon approved these changes

2021-03-16 02:08 UTC, merged